- src/components/buttons/smRoundedBtn.tsx
> [feat] 공용 컴포넌트 추가 : smRoundedBtn

- src/components/buttons/smRoundedBtn.tsx
> [fix] smRoundedBtn: onClick 추가

- src/app/(public)/login/page.tsx
- src/app/(public)/signup/profile/page.tsx
- src/app/(public)/signup/signup.css
- src/components/board/Modal.tsx
로그인 페이지 포탈 api로 변경, 최초 로그인 시에는 프로필 설정 페이지로 이동 후 회원가입되게 변경하였습니다.
> [fix] 최초 로그인 시 루트 변경 완료

- src/app/(auth-required)/main/page.tsx
> [style/fix] 랭킹 부분 gap 적용

- src/api/user/postLogout.tsx
- src/app/(auth-required)/mypage/page.tsx
- src/components/Layout/BottomNav/BottomNav.tsx
> [feat] 로그아웃 구현 완료, 바텀탭 수정 필요

- src/components/buttons/commonBtn.tsx
- 오류 수정 
- - 지우면 안되는걸 지운게 아니라 수정해야 하는 거였음
> [fix] CommonBtn 컴포넌트 : 오류 수정

- src/app/(auth-required)/mypage/edit/page.tsx
- src/components/buttons/commonBtn.tsx
> [fix] 오류 수정 : editProfile(btn자식 요소로 btn 불가)

- src/app/(auth-required)/mypage/edit/page.tsx
> [style] Redesign : 마이페이지 - 프로필 편집

- src/app/(auth-required)/roomstatus/page.tsx
- src/app/(auth-required)/roomstatus/roomItem.tsx
- src/app/(auth-required)/roomstatus/roomItemDetail.tsx
- roomstatus 모바일에서 복사하기 뜨는 오류 해결 중
> [style] select-none 추가 : roomstatus 화면

- src/app/(auth-required)/roomstatus/roomItem.tsx
- roomstatus : 강의 중, 빈강의실 하이라이트 색상 구별
> [perf] roomstatus : 강의 중, 빈강의실 하이라이트 색상 구별

- src/api/chat/postChatImage.tsx
- src/api/clients/apiClient.ts
- src/api/review/getReviewsContext.tsx
- src/api/review/useDepartmentRatingInfoContext.tsx
- src/api/review/useLectureReviewsContext.tsx
- src/api/review/useReviewLikeToggleContext.tsx
- src/api/user/deleteUser.tsx
- src/api/user/postBlockUser.tsx
- src/api/user/postPwCheck.tsx
- src/api/user/putPassword.tsx
- src/api/vote/postVote.tsx
- src/api/vote/postVoting.tsx
> [fix] credential 설정

- src/components/board/CommentSection.tsx
> [fix] 댓글 익명 넘버링 수정

- src/app/(auth-required)/main/boards/[boardName]/create/page.tsx
- src/app/(auth-required)/mypage/page.tsx
로컬스토리지에서 토큰 읽어오는 관련 코드 삭제하였습니다.
> [fix] 글쓰기 토큰관련 수정

- src/components/chat/Message.tsx
- src/components/chat/MessageForm.tsx
- src/components/chat/MessageList.tsx
> [fix] 채팅 읽음표시 수정완료

- src/app/(auth-required)/chat/page.tsx
- src/app/(auth-required)/vote/[voteId]/page.tsx
투표 상세에서 좋아요 스크랩 기능 누락되어있어서 추가하였습니다.
> [fix] 투표 좋아요, 스크랩 기능 수정

- src/app/(auth-required)/chat/page.tsx
- src/components/board/CommentSection.tsx
> [fix] 이미지 깨지는것들 경로 수정

- src/api/chat/getChatRoomData.tsx
- src/components/board/CommentSection.tsx
- src/components/board/pageHeaderModal.tsx
- src/components/modals/AlertModal.tsx
대댓글 삭제 로직이 없어서 추가하였습니다. 
게시글과 댓글 입력창 너비 맞춰놓았는데, 아직 더 수정 필요하니 확인 부탁드립니다
> [fix] 대댓글 삭제 로직 추가 및 게시글과 댓글 입력창 너비 변경.

- src/api/chat/getChatRoomData.tsx
- src/app/(auth-required)/chatRoom/[chatRoomId]/page.tsx
- src/app/(auth-required)/vote/vote.css
- src/components/chat/MessageForm.tsx
> [fix] 투표 시간 css 수정

- src/app/(auth-required)/vote/write/page.tsx
> [fix] 투표 시간 이미지 경로 수정

- src/api/chat/deleteRoom.tsx
- src/api/chat/getChatData.tsx
- src/api/chat/postChatImage.tsx
- src/api/chat/postChatRoom.tsx
- src/api/comment/getComments.tsx
- src/api/comment/postComment.tsx
- src/api/like/postLike.tsx
- src/api/user/deleteUser.tsx
- src/api/user/postBlockUser.tsx
- src/api/user/postLogout.tsx
- src/api/vote/getVoteData.tsx
- src/api/vote/getVoteDetail.tsx
- src/api/vote/postVote.tsx
- src/api/vote/postVoting.tsx
토큰 리이슈 성공 후에 재요청하도록 코드 수정 하였습니다. 일단 제가 담당한부분 api 코드만 바꿨으니 확인해보시고 수정부탁드립니다
> [fix] 토큰 리이슈 코드 수정

- src/app/(auth-required)/main/page.tsx
- src/data/boardData.ts
중고책 > 중고거래
중고 서적 > 중고거래
판매중 > 팝니다
구매중 > 삽니다
위와같이 수정하였습니다
> [fix] 타이틀 수정

- src/app/(auth-required)/main/info/course-reviews/[departmentCode]/page.tsx
- src/app/(auth-required)/main/info/course-reviews/page.tsx
- src/components/Review/DepartmentReview.tsx
- src/components/Review/Subject.tsx
- src/components/modals/AlertModal.tsx
- **What does this PR do?**  
수강 후기 페이지의 헤더, 검색바 퍼블리싱 및 디바운스를 적용한 검색 기능 구현
---
- 🔧 **변경 1**: 과목 코드 표기 삭제
- ✒ **변경 2**: 수강 후기 리스트 가운데 정렬 및 너비 확장
- 📃 **변경 2**: 템플릿 사용시 렌더링 되는 모달의 위치 조정
---
---
_필요한 추가 정보를 여기에 작성해주세요._
> 리뷰페이지 수정 사항 적용

- src/app/(auth-required)/main/info/course-reviews/[departmentCode]/page.tsx
- src/app/(auth-required)/main/info/course-reviews/[departmentCode]/types.ts
- src/app/(auth-required)/main/info/course-reviews/page.tsx
- src/app/(auth-required)/main/info/course-reviews/types.ts
- src/app/(auth-required)/main/info/course-reviews/write-review/page.tsx
- src/components/Review/DepartmentReview.tsx
- src/components/Review/Subject.tsx
- **What does this PR do?**  
수강 후기 페이지에서의 2차 수정 사항 적용
---
- 🔧 **변경 1**: 수강 후기 작성 페이지에서의 공백 수정
- 🔧 **변경 2**: 수강 후기 리스트 컴포넌트에 학기 표기 코드 추가
- 🔧 **변경 3**: 과목별 수강 후기 페이지에 학기, 학년 표기 코드 추가
---
변경1 | 변경2 | 변경3
---|:---:|---:
---
_필요한 추가 정보를 여기에 작성해주세요._
> 리뷰페이지 2차 수정

- src/app/(auth-required)/main/info/course-reviews/write-review/page.tsx
> 💎 style(후기 작성 스타일 수정): 수정

- src/api/like/postLike.tsx
- src/components/Review/DepartmentReview.tsx
- src/components/Review/RateBar.tsx
- src/components/Review/ReviewComment.tsx
수정 사항있다면 디코에 말씀해주시고 머지는 해주지시 말아주세요!!
머지는 무조건 수정사항이 없을 경우에 진행하겠습니다.
> 💎 style(과목별 후기 스타일 수정): 스타일 수정

- src/app/(auth-required)/chat/page.tsx
> [fix] 빌드 에러 수정

- src/app/(auth-required)/chatRoom/[chatRoomId]/page.tsx
> [fix] 채팅방 읽음 표시 오류 해결

- src/app/(auth-required)/chat/page.tsx
쪽지 0개일 때 '채팅을 시작해보세요!' 문구 추가하였습니다
> [feat] 쪽지 0개일 때 '채팅을 시작해보세요!' 문구

- src/app/(auth-required)/roomstatus/roomItem.tsx
- 강의실 현황 : 모서리 시간 클릭 시, 외부로 벗어나는 현상 해결
> [fix] roomstatus : 모서리 시간  클릭시 외부로 벗어나는 문제 해결

- src/components/board/PostItem.tsx
> [fix] PostItem : postStats CSS 수정

- src/app/(auth-required)/main/boards/[boardName]/[postId]/PostDetailClient.tsx
- PostDetailClient : 이미지 아래 마진 추가(수정)
> [fix] PostDetailClient : 이미지 아래 마진 추가(수정)

- src/app/(auth-required)/main/info/course-reviews/page.tsx
- src/components/Review/RateBar.tsx
- src/components/Review/Subject.tsx
> [style] Redesign : rem->px 단위 변경, 여백 최적화

- src/components/Review/DepartmentReview.tsx
- src/components/Review/ReviewComment.tsx
> [style] Redesign : 리뷰 상세 페이지

- src/app/(auth-required)/main/info/course-reviews/write-review/page.tsx
- src/app/(auth-required)/main/info/course-reviews/write-review/util/calcEmotion.ts
- src/components/Review/CustomSelect.tsx
- src/components/Review/RateBar.tsx
> [style] Redesign : 강의 후기 (작성)

- src/components/comment/CommentSection.tsx
- 게시글 상세 : 답글 창이 화면 밖으로 넘어가는 현상 수정
> [fix] 게시글 상세 : 답글 창이 화면 밖으로 넘어가는 현상 수정

- src/app/(auth-required)/chat/page.tsx
채팅 리스트 검색버튼 동작이 원활하지 않아 수정 후 다시 올리도록 하겠습니다.
> [fix] 채팅 검색버튼 삭제

- src/app/(public)/login/loginAnimation.css
- src/app/(public)/login/page.tsx
> [style] 로그인 : 로그인 버튼 늦게 생성

- src/app/(auth-required)/main/page.tsx
- src/app/(public)/login/page.tsx
- 로그인 말풍선 3초 뒤 등장
- 메인 캘린더 아래 여백 축소
> [style] Redesign : 로그인 말풍선 3초 뒤 등장 & 메인 캘린더 아래 여백 축소

- src/components/Review/ReviewComment.tsx
- Redesign : 강의 상세 -> 댓글 여러개일 때 깨지는 현상 수정
> [style] Redesign : 강의 상세 -> 댓글 여러개일 때 깨지는 현상 수정

- src/app/(auth-required)/vote/[voteId]/page.tsx
-  파일 삭제 후 build 오류 : vote.css 제거
> [fix] 파일 삭제 후 build 오류 : vote.css 제거

- src/app/(auth-required)/main/boards/[boardName]/[postId]/PostDetailClient.tsx
- src/components/comment/CommentSection.tsx
- 대대댓글 구현 ( 대대댓글 작성시 @닉네임으로 대댓글 닉네임 언급)
- 댓글 레이아웃 깨지는 현상 수정
> [feat] 대대댓글 구현 : 자동태그 @닉네임

- src/components/comment/CommentSection.tsx
- 레이아웃 유지를 위한 플레이스홀더 설정
- 언급 없이 @만 출력되는 오류 수정
> [perf] 대대댓글 : 레이아웃 유지를 위한 플레이스홀더 설정

- src/app/(auth-required)/roomstatus/page.tsx
- src/app/(auth-required)/roomstatus/roomItem.tsx
- src/app/(auth-required)/roomstatus/roomItemDetail.tsx
- src/app/(auth-required)/roomstatus/styles/roomItem.module.css
> [style] 강의실 현황 접근성 개선 

- src/app/(auth-required)/roomstatus/components/roomItem.tsx
> [style] 사이즈를 전역 변수로 변경

- src/app/(auth-required)/roomstatus/components/roomItem.tsx
> [fix] gap 적용되지 않는 버그 수정

- src/app/(auth-required)/roomstatus/constants/timeTableSize.tsx
> [style] 타임테이블 크기 조정

- src/components/Layout/BottomNav/BottomNav.tsx
> [style] bottomNav: z-index증가

- src/app/(auth-required)/roomstatus/components/roomItem.tsx
> [style] roomItem : 세로 길이 증가

- src/app/(public)/login/loginAnimation.css
- src/app/(public)/login/page.tsx
> [feat] 로그인 버튼 인터랙션 : 공지 강조 & 애니메이션 추가

- src/app/(public)/login/page.tsx
> [fix] 로그인 href 복구

- src/app/(auth-required)/roomstatus/components/roomItem.tsx
- src/app/(auth-required)/roomstatus/constants/timeTableData.tsx
> [style] roomstatus : 타임테이블 미세조정

- src/app/(public)/login/page.tsx
- 로그인 : 기존 2.5초 안내 -> 새로운 인터랙션으로 이동
> [style] 기존 2.5초 안내 -> 새로운 인터랙션으로 이동

- src/components/Layout/BottomNav/BottomNav.tsx
> [fix] btmNav : z 50 -> 45

- src/app/(auth-required)/main/page.tsx
메인에서 캘린더 변경이후 마진이 적어보인다 그래서 마진 한부분만 늘렸습니다
> 메인 메뉴 탑마진 증가

- src/app/(auth-required)/chatRoom/[chatRoomId]/page.tsx
- src/app/(auth-required)/ticketing/[eventId]/page.tsx
- src/components/chat/MessageForm.tsx
- 채팅 버튼 안눌리는 문제 확인
- 뒤로가기 버튼 경로지정
읽음 처리가 제대로 안되는 경우 확인하였음. 어느쪽 문제인지 확인해야 할 필요 있음
> fix(QA 1): 채팅부분

- src/app/(auth-required)/boards/[boardName]/create/page.tsx
- src/app/(auth-required)/chatRoom/[chatRoomId]/chatRoom.css
- src/app/(auth-required)/chatRoom/[chatRoomId]/page.tsx
- src/app/(auth-required)/vote/[voteId]/page.tsx
- src/app/(auth-required)/vote/page.tsx
- src/app/(auth-required)/vote/write/page.tsx
- src/components/chat/MessageForm.tsx
- 채팅 버튼 막히는 문제 수정 (이미지버튼은 미해결)
- 투표 게시글 좋아요 안되는 문제 해결
- 투표 옵션 선택안했을 시 전송막기
- 메인 경유시에 버튼 안먹는 문제 원인 파악하기
> fix(QA 2): 투표 및 채팅 문제해결

- src/api/boards/getSearch.ts
- src/app/(auth-required)/boards/page.tsx
- src/app/(auth-required)/search/page.tsx
- src/components/Layout/BoardLayout.tsx
- src/components/Layout/header/SearchButton.tsx
- src/components/board/PostItem/ListWithCategoryPostItem.tsx
- src/components/board/PostItem/utils.ts
- src/data/boardData.ts
- 검색페이지 정상작동하도록 수정
- /board 페이지 검색기능 추가
- 검색 결과 투표 게시글도 정상적으로 보이게 수정
- 검색 결과 게시글 카테고리 더 세분화
- 각 페이지에서 검색버튼 삭제 또는 검색페이지로 이동 중 선택하기 (현재는 검색페이지로 이동)
> feat(QA 2) : 검색기능 추가

- next.config.ts
- src/app/(auth-required)/chatRoom/[chatRoomId]/page.tsx
- src/components/Layout/BoardLayout.tsx
- 비교과 next image 관련한 오류 수정
- 게시판 헤더와 탭 컴포넌트 사이 빈공간 채우기
- 채팅방 제목이 너무 길 경우 넘치는 문제 해결
- 자잘한 이슈 수정 및 추가 테스트
> fix(QA 2): 검색기능 추가 및 기타 이슈 수정

- src/app/(public)/login/admin/page.tsx
- 관리자 로그인 경로 수정
- 
- 
(작업 내역 스크린샷)
> [fix] 관리자 로그인 경로 수정

- src/app/(auth-required)/ticketing/[eventId]/page.tsx
- src/app/(auth-required)/ticketing/result/TicketingResultInner.tsx
- src/app/(auth-required)/ticketing/result/page.tsx
- 티켓팅 페이지 하단버튼 아래쪽 네비바에 가려지는 문제 - > 스타일 수정
- 
- #280 
(작업 내역 스크린샷)
> [style] 티켓팅 페이지 스타일 수정

- src/app/(public)/vote/page.tsx
- 투표 글쓰기 href 수정 (  /vote/wirte -> /wirte/vote )
- 
- #279 
(작업 내역 스크린샷)
> [fix] 투표 글쓰기 href 수정

- src/components/modals/ticketing/AdminPasswordModal.tsx
> [fix] 비밀번호 확인 후 새로고침 추가
